name: "Local Upload Artifact"
description: "Upload artifact manually"
inputs:
  name:
    description: "Name of the artifact"
    required: true
  path:
    description: "Path to artifact"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        mkdir -p artifacts
        cp -r ${{ inputs.path }} artifacts/${{ inputs.name }}
      shell: bash

