name: Compile LaTeX Document

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:
    branches:
      - main   # Anda bisa memilih cabang lain jika diperlukan
  pull_request:
    branches:
      - main   # Akan memicu kompilasi saat ada pull request

jobs:
  compile:
    runs-on: ubuntu-latest  # Menjalankan di lingkungan Ubuntu terbaru

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Checkout repository (Local)
        uses: ./.github/actions/checkout  # Memastikan kode repositori di-checkout ke dalam runner
      
      - name: Cache TeX Live
        id: cache-texlive
        uses: actions/cache@v4.2.2
        with:
          path: docs/texlive-cache
          key: ${{ runner.os }}-texlive
          restore-keys: |
            ${{ runner.os }}-texlive-

      - name: Use or Generate the texlive-cache
        if: ${{ steps.cache-texlive.outputs.cache-hit != 'true' }}
        run: /generate-texlive.sh -d texlive-cache

      - name: Use texlive
        run: /texlive.sh -d texlive-cache

      - name: Verify we have our cached file
        run: ls cache-folder

      - name: Set up TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
        # Ini akan menginstal TeX Live, distribusi LaTeX yang dibutuhkan untuk kompilasi
      - name: Ensure docs directory exists
        run: mkdir -p docs && chmod 777 docs

      - name: Compile LaTeX file to PDF
        run: pdflatex -interaction=nonstopmode -output-directory=docs main.tex  # Sesuaikan dengan nama file LaTeX utama Anda
        
      - name: List files
        run: ls -l  # Akan menampilkan file yang ada di dalam direktori
      
      - name: Create docs directory
        run: mkdir -p docs
        
      - name: Upload PDF artifact
        uses: ./.github/actions/upload-artifact  # Upload PDF hasil kompilasi
        with:
          name: output-pdf  # Nama untuk file yang di-upload
          path: docs/main.pdf    # Sesuaikan dengan nama file PDF hasil kompilasi Anda
      
      - name: Configure Git User
        run:  |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Check if PDF changed
        run:  |
          if ! git diff --quiet docs/main.pdf; then
            git add docs/main.pdf
            git commit -s -m "Compiled PDF [Update]"
            git push origin main
          fi
