name: Kompilasi Dokumen LaTeX

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest  # Menjalankan di lingkungan Ubuntu terbaru

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0 # Pastikan riwayat lengkap untuk perbandingan Git
      
      - name: Cache TeX Live
        id: cache-texlive
        uses: actions/cache@v4.2.2
        with:
          key: ${{ runner.os }}-texlive-2024
          restore-keys: |
            ${{ runner.os }}-texlive-
          path: $HOME/texlive

      - name: Restore Cache TeX Live
        id: cache-texlive-restore
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-texlive-2024
          path: $HOME/texlive

      - name: Always save Cache of TeX Live
        id: cache-texlive-save
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.cache-texlive-restore.outputs.cache-primary-key }}
          path: $HOME/texlive

      - name: Make Scripts Executable
        run: chmod +x scripts/generate-texlive.sh scripts/texlive.sh

      - name: Install TeX Live (if not cached)
        if: steps.cache-texlive.outputs.cache-hit != 'true'
        run: scripts/generate-texlive.sh $HOME/texlive

      - name: Use Cached TeX Live
        run: scripts/texlive.sh $HOME/texlive main
        
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4.6.1  # Upload PDF hasil kompilasi
        with:
          name: output-pdf  # Nama untuk file yang di-upload
          path: docs/main.pdf    # Sesuaikan dengan nama file PDF hasil kompilasi Anda
